language: python
python:
    - "2.7"

sudo: required
        
branches:
    - master
  
env:
    global:
        - USR_NAME="OlafFilies"
        - USR_EMAIL="Olaf.Filies@infineon.com"
    matrix:
        - PLATFORMIO_CI_SRC=examples/Control2Motors 
        - PLATFORMIO_CI_SRC=examples/rampSpeedTest
        - PLATFORMIO_CI_SRC=examples/rampTest
        - PLATFORMIO_CI_SRC=examples/speedControl

install:
    # build with stable core
    - pip install -U platformio
    - platformio platform install -f infineonxmc
    - platformio platform install -f atmelavr

script:
    - platformio ci --lib="."  --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno

after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        #git clone https://github.com/Infineon/InfineonDoxyGenerator.git
        cd InfineonDoxyGenerator/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi
